cloudgate:
  required_version: '~> 8.1.0'
app:
  name: light-bikes
  users:
    mgreen:
      name: Mel Green
      email: mgreen@instructure.com
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT/kn79HPypnELxS07Pn8clwspie4xB7QSXKe3gCfx5JKrFL6L0w9GCpP72SGZ4JWQ0jjIxyopE57hM066oa4Z22NHtsmM6JYq9zl6jVfKx+t9ucHQFxODRv75AAhWyW21a2APcO4E843p2W5GZsSDO9+loWi4qr+DkPI8nKszKCojZOaYod+2RW8/+eKQ/weaECMC9r3q1GivSGfiiWbh75wUQ8Ik8S3j3e4pDmGgR9aEim3U66XAKaA6Xhq+VALRF6MdnUK0H4y6pht8XsI8FstcFjhLYRp0YK6bxZGMzuqSuF1cn4ZrUWY1PYQemAXCSoZHzGjo2z3CCxoOEYCL mgreen@mgreen-l.corp.instructure.com
    dhyer:
      name: Davis Hyer
      email: dhyer@instructure.com
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzThPLbXvFAjXGrdd/Gq7XlyV3WIwzd7p765Mu85hsmFdl1bZpS+ws1QzKYwPKvBG7qHBK0cgWkh/IFj407C4LBcG/UBpnCVBUwAIAF7vgc7qrj2cvR9C1Zx5DqteNdorGw766kOaI+4fq9IpiWYacbtTnypPECtMhTWlKCgN91NdIgKHsQwVMn0hHa8Ntp+IDgj3+Q+CRloUFRLvUbfO+yIZh+kpE5UEvvSSVOiY/GgF8v03aWNf8CwUQi6p2TRvzhbkzsM49TWQXIJWsGkPZ2tasLvYbNID1u32+h7RKg0sAhkvHXgFVLOfqO3zfPn1CVC6bIFjaPV1XgGZJVtiN dhyer@dhyer-l2.corp.instructure.com.corp.instructure.com
    bnelson:
      name: Ben Nelson
      email: bnelson@instructure.com
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC51OKo8bFL/Ny2GRjkh6KcRrjcQCyBqH3On/SGL8H0yNCBLWqayrwCU06t+OfhfsT1bOs+rAc4M9yCbOjlTTeRQHZDfySkRYVpAQkEB2e6ypIvBXAhvnLYXTI/IcKZg4ODxFDFaNOyr2w/kw6MbAKkalbhLcy06myYBUzJmheDkSY8UVYXj1gnc6ZBMHpBV1JU4b8+s1c/79S4yqvNWbUBRB8fjaTK4CjC8Ycy1o+tPuEPd+3YLdTDOlv3oWCyqZ7bsOMUIjMBt5jcVNO2F5s9NLXw89FKfwipHrBmso66BV48NB9wFcCwsrfBBzRjs2h691zMjgpnRMCXXv+H/GxRFOdtvKVOcsU5S03XamaPMNa11SbO7LxUjnIxks2qTk+Pjj6nkza7JFfgW7BZ8iuNVpnrvDjVNjBiyYXzUuGOk2geLvajG05INZcjMnxRK1JjJ0FsSFOatyFwaaMT/6lws1NtF8Z6ibZu/1Ozg0WmvqwPM3okNVXck1oLdGJD4yc= bnelson@c02zc2wblvdr.corp.instructure.com
  load_balancers:
    web:
      ssl_cert_arn: "arn:aws:acm:us-west-2:830473435438:certificate/b119c8b6-9305-4532-9798-dcfbf712158b"
  instance_pools:
    web:
      http_port: 8080
      health_check_path: /health-check
      instance_type: m5.4xlarge
      max_size: 1
      min_size: 1
      env_vars:
        LOG_LEVEL: 'info'
        UI_CORS_URL: http://light-bikes-ui.s3-website-us-west-2.amazonaws.com/
