cloudgate:
  required_version: '~> 7.0.0'
app:
  name: light-bikes
  users:
    mgreen:
      name: Mel Green
      email: mgreen@instructure.com
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT/kn79HPypnELxS07Pn8clwspie4xB7QSXKe3gCfx5JKrFL6L0w9GCpP72SGZ4JWQ0jjIxyopE57hM066oa4Z22NHtsmM6JYq9zl6jVfKx+t9ucHQFxODRv75AAhWyW21a2APcO4E843p2W5GZsSDO9+loWi4qr+DkPI8nKszKCojZOaYod+2RW8/+eKQ/weaECMC9r3q1GivSGfiiWbh75wUQ8Ik8S3j3e4pDmGgR9aEim3U66XAKaA6Xhq+VALRF6MdnUK0H4y6pht8XsI8FstcFjhLYRp0YK6bxZGMzuqSuF1cn4ZrUWY1PYQemAXCSoZHzGjo2z3CCxoOEYCL mgreen@mgreen-l.corp.instructure.com
    dhyer:
      name: Davis Hyer
      email: dhyer@instructure.com
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzThPLbXvFAjXGrdd/Gq7XlyV3WIwzd7p765Mu85hsmFdl1bZpS+ws1QzKYwPKvBG7qHBK0cgWkh/IFj407C4LBcG/UBpnCVBUwAIAF7vgc7qrj2cvR9C1Zx5DqteNdorGw766kOaI+4fq9IpiWYacbtTnypPECtMhTWlKCgN91NdIgKHsQwVMn0hHa8Ntp+IDgj3+Q+CRloUFRLvUbfO+yIZh+kpE5UEvvSSVOiY/GgF8v03aWNf8CwUQi6p2TRvzhbkzsM49TWQXIJWsGkPZ2tasLvYbNID1u32+h7RKg0sAhkvHXgFVLOfqO3zfPn1CVC6bIFjaPV1XgGZJVtiN dhyer@dhyer-l2.corp.instructure.com.corp.instructure.com
  instance_pools:
    web:
      http_port: 8080
      https_port: 8443
      health_check_path: /health-check
      instance_type: t2.micro
      max_size: 1
      min_size: 1
      env_vars:
        LOG_LEVEL: 'info'
        UI_CORS_URL: http://light-bikes-ui.s3-website-us-west-2.amazonaws.com/
